services:
  server:
    build: ./website/server
    ports:
      - 3000:3001

  database:
    build: ./Database

  client:
    build: ./website/client
    ports:
      - 5000:5173

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8001:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
